wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.8
    cli_version: 0.16.3
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1709231570.953152
    t:
      1:
      - 2
      - 3
      - 55
      2:
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 3
      - 8
      - 19
      - 23
      4: 3.11.8
      5: 0.16.3
      8:
      - 3
      - 5
      10:
      - 1
      - 9
      13: windows-amd64
dense_layer_size:
  desc: null
  value: 2
epochs:
  desc: null
  value: 10
optimizer:
  desc: null
  value: adam
hidden_nodes:
  desc: null
  value: 100
