wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.8
    cli_version: 0.16.3
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1709222747.006145
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 23
      4: 3.11.8
      5: 0.16.3
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
