wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.8
    cli_version: 0.16.3
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1709226025.564339
    t:
      1:
      - 2
      - 3
      - 55
      2:
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 19
      - 23
      4: 3.11.8
      5: 0.16.3
      8:
      - 3
      - 5
      13: windows-amd64
img_width:
  desc: null
  value: 28
img_height:
  desc: null
  value: 28
first_layer_conv_width:
  desc: null
  value: 3
first_layer_conv_height:
  desc: null
  value: 3
dense_layer_size:
  desc: null
  value: 25
epochs:
  desc: null
  value: 10
optimizer:
  desc: null
  value: adam
